---

- name: Ensure snapd is installed
  become: true
  apt:
    name: snapd
    state: present

- name: Ensure snapd is running
  service:
    name: snapd
    state: started
    enabled: true

- name: Install snap packages
  snap:
    name: "{{ item.name }}"
  loop: "{{ snap_packages }}"
