---
- name: docker | Manual - create directories
  file:
    dest=/etc/docker/daemon.json
    recurse=yes
    state=directory
    owner=root
    group=root

- name: Make docker configuration file.
  template:
    src: /etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Restart service docker and daemon-reload to pick up config changes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker
