---
- hosts: ubuntu-servers
  become: true
  gather_facts: yes
  name: install and configure ubuntu server
  roles:
  # preparing server and hardening
#    - { role: preparing_server, become: True, tags: preparing_server }
  # install and configure docker service
    - role: docker
      tags: install-docker