---
- name: apt update
  become: true
  apt:
    upgrade: no
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Restart snapd service
  service:
    name: snapd
    state: restarted
  become: yes