all:
    children:
        servers:
            hosts:
#                mhykari-sharif:
#                    ansible_host: mhykari-sharif
#               jb-sharif:
#                   ansible_host: jb-sharif
#                adrian-sharif:
#                    ansible_host: adrian-sharif
#               taban-sharif:
#                   ansible_host: taban-sharif
#               ehtesabi-sharif:
#                   ansible_host: ehtesabi-sharif
#               ponisha-sharif:
#                   ansible_host: ponisha-sharif
#               lyan-sharif:
#                   ansible_host: lyan-sharif
               lyan-v2ray:
                   ansible_host: lyan-v2ray
               mhykari-2-ista:
                   ansible_host: mhykari-2-ista
               mhykari-2-v2ray:
                   ansible_host: mhykari-2-v2ray
               mhykari-usa:
                   ansible_host: mhykari-usa