---
- name: Check if Zabbix agent is installed
  ansible.builtin.package_facts:

- name: Remove Zabbix agent if installed
  ansible.builtin.apt:
    name: zabbix-agent
    state: absent
  when: ansible_facts.packages['zabbix-agent'] is defined

- name: Download Zabbix release package
  ansible.builtin.get_url:
    url: "{{ zabbix_agent2_url }}"
    dest: /tmp/{{ zabbix_agent2_deb }}

- name: Install Zabbix release package
  ansible.builtin.apt:
    deb: /tmp/{{ zabbix_agent2_deb }}
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Zabbix agent2
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix Agent 2
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Zabbix Agent 2

- name: Enable Zabbix Agent 2 service
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: yes

### Uncomment if you want to monitor docker containers with zabbix agent 2
- name: Add zabbix user to the docker group
  command: usermod -aG docker zabbix
  become: true
  notify:
    - Restart Zabbix Agent 2